In [1]:
import numpy as np

In [2]:
data = np.random.randn(2,3)

In [3]:
data

array([[-0.04867452, -0.23513398,  0.71376862],
       [-0.0268257 ,  0.45642933,  0.39041783]])

In [4]:
type(data)

numpy.ndarray

In [5]:
data*10

array([[-0.48674517, -2.35133983,  7.13768616],
       [-0.26825703,  4.56429326,  3.90417826]])

In [6]:
data+data

array([[-0.09734903, -0.47026797,  1.42753723],
       [-0.05365141,  0.91285865,  0.78083565]])

In [7]:
data.shape

(2, 3)

In [8]:
data.dtype

dtype('float64')

### Creating ndarrays

In [9]:
data1 = [1, 2, 3, 4.5, 6]

In [11]:
arr1 = np.array(data1)

In [12]:
arr1

array([1. , 2. , 3. , 4.5, 6. ])

In [13]:
type(arr1)

numpy.ndarray

In [14]:
arr1.dtype

dtype('float64')

In [26]:
data2 = [[1,2,3,4], [5,6,7,8]]

In [27]:
arr2 = np.array(data2)

In [28]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [29]:
arr1.shape

(5,)

In [30]:
arr2.shape

(2, 4)

In [31]:
arr2.dtype

dtype('int64')

###### ndim: numero de dimensões do array

In [32]:
arr1.ndim

1

In [33]:
arr2.ndim

2

### Indexing and Slicing

In [34]:
arr = np.arange(10)

In [35]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
arr[5]

5

In [37]:
arr[5:8]

array([5, 6, 7])

In [38]:
arr[5:8] = 12

In [39]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [55]:
arr_slice = arr[5:8]

In [41]:
arr_slice

array([12, 12, 12])

In [42]:
arr_slice[1] = 12345

In [43]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [50]:
arr_slice[:] = 64

In [51]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [46]:
arr_slice[-1] = -1

In [47]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, -1,  8,  9])

In [48]:
arr_slice[:-1] = 0

In [52]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [53]:
arr_slice[1:] = 0

In [54]:
arr

array([ 0,  1,  2,  3,  4, 64,  0,  0,  8,  9])

##### Slicing em Matrizes

In [56]:
arr2d = np.array([[ 1, 2, 3, 4], 
                  [ 5, 6, 7, 8],
                  [ 9,10,11,12],
                  [13,14,15,16]])

In [57]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [58]:
arr2d[0][2]

3

In [59]:
arr2d[0,2]

3

In [60]:
arr2d[0:3, 0:3]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

#### Tentando caminha na matriz pegando pequenas matrizes 3x3

In [62]:
arr2d.shape

(4, 4)

In [63]:
linhas = arr2d.shape[0]
colunas = arr2d.shape[1]

In [64]:
linhas, colunas

(4, 4)

In [66]:
for l in range(linhas):
    print(l)

0
1
2
3


In [68]:
for l in range(linhas):
    for c in range(colunas):
        print(l, c)

0 0
0 1
0 2
0 3
1 0
1 1
1 2
1 3
2 0
2 1
2 2
2 3
3 0
3 1
3 2
3 3


In [70]:
for l in range(linhas):
    for c in range(colunas):
        print(str((l, c)) + ': ' + str(arr2d[l,c]))

(0, 0): 1
(0, 1): 2
(0, 2): 3
(0, 3): 4
(1, 0): 5
(1, 1): 6
(1, 2): 7
(1, 3): 8
(2, 0): 9
(2, 1): 10
(2, 2): 11
(2, 3): 12
(3, 0): 13
(3, 1): 14
(3, 2): 15
(3, 3): 16


In [71]:
for l in range(1, linhas-1):
    for c in range(1, colunas-1):
        print(str((l, c)) + ': ')
        print(arr2d[l-1:l+2, c-1:c+2])

(1, 1): 
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]
(1, 2): 
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]
(2, 1): 
[[ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
(2, 2): 
[[ 6  7  8]
 [10 11 12]
 [14 15 16]]
